# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 1
project_name: dot

before:
  hooks:
  - go mod tidy
  - go generate ./...

builds:
- id: dot
  main: ./cmd/dot/
  binary: dot
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  goarm:
  - '6'
  - '7'
  flags:
  - -trimpath
  ldflags:
  - -s -w
  env:
  - CGO_ENABLED=0

archives:
- name_template: >-
    {{ .ProjectName }}_
    {{- .Version }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{- .Arch }}{{- end }}
    {{- if .Arm }}v{{- .Arm }}{{- end }}

snapshot:
  name_template: "snapshot-{{ .ShortCommit }}"

checksum:
  name_template: 'checksums.txt'
signs:
- artifacts: checksum
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
